### ISSUE TITLE
增加标签功能?

### ISSUE THREAD

**Issue by izuolan** [hoythan/Git-Remarks#2]
参考这个: https://github.com/gabrielgodoy/github-stars-manager

上面这个插件的作者更新有点迷, 有时甚至删了整个仓库重来. 而且要求权限特别大, 不是很放心.

我看你演示也有添加标签功能的打算?

**Comment by hoythan** [comment]
确有打算，正在设计

**Comment by izuolan** [comment]
那我保持关注, issue关了.
