### ISSUE TITLE
能否增加一个下载文件的功能？

### ISSUE THREAD

**Issue by jerry011235** [hoythan/Git-Remarks#3]
左键单击 文件/文件夹 左侧的图标 即可下载 该文件/文件夹。
![2](https://user-images.githubusercontent.com/12509976/39519621-12738104-4e3a-11e8-8d6c-d118bc704ba9.png)

如果可以的话，能否把 [chrome-github-mate](https://github.com/camsong/chrome-github-mate) 的功能照搬过来，因为它的下载功能失效了，而github-mate的作者似乎很少更新了。

**Comment by hoythan** [comment]
主要用于备注功能。
