### ISSUE TITLE
列表页看不到备注信息，详情页正常

### ISSUE THREAD

**Issue by jae-jae** [hoythan/Git-Remarks#6]
插件版本:1.0.2
系统: MacOS
浏览器：Chome66

列表页看不到备注：
![image](https://user-images.githubusercontent.com/5620429/40952924-090e5284-68b0-11e8-8ee7-b22694d67c58.png)

详情页正常：
![image](https://user-images.githubusercontent.com/5620429/40952950-1ebb9042-68b0-11e8-9b53-cb261ac106fd.png)

**Comment by hoythan** [comment]
已经修复，可以在应用商店直接更新，或者下载根目录下的 `git remarks.crx` 文件。
